name: LearningToCountAnything
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - cudatoolkit=10.2.89
  - einops=0.3.2
  - matplotlib=3.4.3
  - numpy=1.22.3
  - pillow=9.0.1
  - pip=21.2.4
  - python=3.8.13
  - pytorch=1.8.0
  - pytorch-lightning=1.5.1
  - tensorboard=2.9.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - torchmetrics=0.8.2
  - torchvision=0.9.0
  - tqdm=4.64.0
  - pip:
    - lightning-bolts==0.5.0
    - timm==0.6.2.dev0
