---
seed: -1
resume_path: logs/examples/localisation.ckpt
dataset: FSC-133

backbone: "vit_dino"
backbone_unfreeze_layers: 0

use_counting_head: False

total_loss: localisation_loss
use_localisation_head: True
localisation_head: conv
localisation_loss: MSE
tensorboard_visualise_localisation: True
save_visualise_localisation: True

image_transforms: reflect_rotate 

train_batch_size: 16
eval_batch_size: 16

learning_rate: 0.0

max_epochs: 1




