---
seed: -1
resume_path: logs/examples/counting.ckpt
dataset: FSC-133

backbone: "vit_dino"
backbone_unfreeze_layers: 7

counting_head: linear
counting_loss: MAPE
pca_visualise: True
save_visualise_localisation: True

image_transforms: reflect_rotate_increase_density 

train_batch_size: 16
eval_batch_size: 16

learning_rate: 0.0
max_epochs: 1



